In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


## Introduction to Tensors

### Creating Tensors

In [ ]:
# Scaler
scaler = torch.tensor(7)
scaler

tensor(7)

In [ ]:
# Scaler have no dimention
scaler.ndim

0

In [ ]:
# Get tensor back as a Python int
scaler.item()

7

In [ ]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7,9],[9,10]])
MATRIX

tensor([[ 7,  9],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 9])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR[0][2][1]

tensor(4)

In [ ]:
tensor1 = torch.tensor([[
    [1,2,3],
    [4,5,6],
    [7,8,9]
],[
    [10,11,12],
    [13,14,15],
    [16,17,18]
]])
tensor1

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])

In [ ]:
tensor1[1][1][2]

tensor(15)

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networds learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [ ]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.7302, 0.2559, 0.5805, 0.1720],
        [0.1544, 0.4292, 0.1768, 0.3488],
        [0.7373, 0.5704, 0.7437, 0.9735]])

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # color channel, height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeroes and ones

In [ ]:
# Create a tensor of all zeroes
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [ ]:
one_to_ten = torch.arange(0, 11, 1) # or torch.arange(start = 0, end = 1000, step = 77)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Create tensors like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

**Note:** Tensor datatypes is one of the 3 bug errors you'll run into with PyTorch and deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [ ]:
# FLoat 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None, # What datatype is tensor
                               device = None, # What deviec is your tensor on
                               requires_grad = False) # Whether or not track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
 float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3,6,9],
                             dtype = torch.int64)
int_32_tensor

tensor([3, 6, 9])

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

# Getting information from tensors(tensor attributes)

1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [ ]:
# Creat a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.0131, 0.3754, 0.5104, 0.3466],
        [0.4503, 0.5906, 0.8061, 0.5639],
        [0.1635, 0.1514, 0.5846, 0.4413]])

In [ ]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.0131, 0.3754, 0.5104, 0.3466],
        [0.4503, 0.5906, 0.8061, 0.5639],
        [0.1635, 0.1514, 0.5846, 0.4413]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include
* Addition
* Subtraction
* Multiplication
* Division
* Martix manupulation

In [ ]:
# Create a Tensor
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiply by 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
# Substract 10
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# Try out tensor in-buils function
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimension** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work

2. The resulting matrix has the shape if the **outer dimernsions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`

In [ ]:
torch.rand(3,2)

tensor([[0.7145, 0.5944],
        [0.5318, 0.9971],
        [0.9905, 0.0362]])

In [ ]:
torch.matmul(torch.rand(3, 10), torch.rand(10, 3))

tensor([[1.3349, 1.8808, 1.8362],
        [2.1567, 2.6845, 3.0971],
        [1.6627, 2.1847, 2.8501]])

In [ ]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
%%time
# Matrix Multiplication by hand
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]

print(value)

tensor(14)
CPU times: user 1.76 ms, sys: 0 ns, total: 1.76 ms
Wall time: 1.99 ms


In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 78 µs, sys: 13 µs, total: 91 µs
Wall time: 95.4 µs


tensor(14)

### One of the most common errors in deep learining: shape errors

In [ ]:
# Shapes for matrix multiplications
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                        [8,11],
                        [9, 12]])

#torch.mm(tensor_A, tensor_B) # torch.mm does the same job as matmul
#torch.matmul(tensor_A, tensor_B) # This tensor will throw an error since the shape is(3, 2) (3, 2)

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix the tensor shape issues, we can manipulate the shape of our tensors using a **Transpose**

A **transpose** switches the axes or dimensions of a given tensor

In [ ]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [ ]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
# The matrix manilulation operation words when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimension must match")
print("Output: \n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"Output shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimension must match
Output: 

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
Output shape: torch.Size([3, 3])


### Finding the min, max, mean, sum etc(tensor aggregation)

In [ ]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# Find the mean
#torch.mean(x) # Will throw an error, datatype must be float or complex, following is "Long"

torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Finding the postion in tensor that has the minumum value with argmin() -> returns the index of the minimum value in the tensor
x.argmin()

tensor(0)

In [ ]:
# Find the max value index using argmax()
x.argmax()

tensor(9)

 ## Reshaping, stacking, sqeezing and unsquuezing tensors

 * Reshaping - reshapes an input tensor to a defined shape
 * View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
 * Stacking - combime multiple tensors on top of each other(vstack) or side by side(hstack)
 * Squueze - remove all `1` dimensions from a tensor
 * Unsqueeze - add a `1` dimension to a target tensor
 * Permute - Return a view of the input with demension permuted(swapped) in a certain way

In [ ]:
# Let's create a tensor
x = torch.arange(1., 10.,)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x beacause a view of a tensor shares the same memoey as the original input
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tesnor on top of eachother
x_stacked = torch.stack([x, x, x, x], dim = 0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous Shape: {x_reshaped.shape}")

x_squeezed = x_reshaped.squeeze()
print(f"\nNew Tensor: {x_squeezed}")
print(f"New Shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous Shape: torch.Size([1, 9])

New Tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New Shape: torch.Size([9])


In [ ]:
# torch.unsqueeze() - adds a single dimension to a target at a spexific dim(dimension)
print(f"Previous Target: {x_squeezed}")
print(f"Previous Shape: {x_squeezed.shape}")

# Add an extra dimension with Unsqueeze
x_unsqueeze = x_squeezed.unsqueeze(dim = 0)
print(f"\nNew Tensor: {x_unsqueeze}")
print(f"New Shape: {x_unsqueeze.shape}")

Previous Target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous Shape: torch.Size([9])

New Tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New Shape: torch.Size([1, 9])


In [ ]:
# torch.permute - rearranges the dimension of a target tensor in a specific order
x_original = torch.rand(224, 224, 3) # height, weight, color_channels

# Permute the original tensor to rearrange the axis(or dim) order
x_permuted = x_original.permute(2, 0, 1)

print(f"Precious Shape: {x_original.shape}")
print(f"New Shape: {x_permuted.shape}") # [color_channels, height, width]

Precious Shape: torch.Size([224, 224, 3])
New Shape: torch.Size([3, 224, 224])


In [ ]:
x_original

tensor([[[0.7471, 0.6273, 0.1168],
         [0.0779, 0.4393, 0.7959],
         [0.3808, 0.6297, 0.7625],
         ...,
         [0.5076, 0.7950, 0.8530],
         [0.5270, 0.8391, 0.8438],
         [0.3324, 0.4255, 0.5790]],

        [[0.9200, 0.8315, 0.3939],
         [0.4756, 0.0707, 0.8420],
         [0.4156, 0.8647, 0.2982],
         ...,
         [0.9091, 0.7254, 0.6773],
         [0.6515, 0.4054, 0.8749],
         [0.7491, 0.9740, 0.2710]],

        [[0.6277, 0.4260, 0.8100],
         [0.3750, 0.0023, 0.7380],
         [0.0740, 0.6892, 0.1995],
         ...,
         [0.7969, 0.1993, 0.3936],
         [0.3125, 0.5060, 0.1225],
         [0.5439, 0.5483, 0.9572]],

        ...,

        [[0.3753, 0.5169, 0.9535],
         [0.5798, 0.0875, 0.4511],
         [0.4997, 0.3714, 0.2689],
         ...,
         [0.9483, 0.7761, 0.9898],
         [0.4252, 0.3676, 0.3820],
         [0.5210, 0.8539, 0.1013]],

        [[0.7678, 0.1454, 0.1263],
         [0.5279, 0.3371, 0.5454],
         [0.

In [ ]:
x_original[0, 0, 0] = 176643
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(176643.), tensor(176643.))

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [ ]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Index on middle bracket(dim = 1)
x[0, 0]

tensor([1, 2, 3])

In [ ]:
# Index on the most inner barcket(last Dimension)
x[0, 0, 0]

tensor(1)

In [ ]:
# We can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
# Get all the values of 0th and 1st dimension but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of the 0 dimension but only the 1 index of 1st and 2nd dimension
x[:, 1, 1] # the "[]" around the 5 is because of the ":", replace it with "0" to get the value only

tensor([5])

In [ ]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [ ]:
x[:, :, 2]

tensor([[3, 6, 9]])

## PyTorch tensors and Numpy

Nympy is a popular scientifix Python numerical computing library
Beause of this, PyTorch has functionality to interact with it

* Data in Numpy, want in PyTorch Tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> Numpy -> `torch.Tensor.numpy()`

In [ ]:
# NumPy array to tensor

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # When converting from numpy -> pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Change the value of array, what will this do to 'tensor'?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor -> NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Change the tensor, what happens to 'numpy_array'?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short how a neural network learns:
`start with random numbers -> tensor operations -> updatw random numbers to try and make better representation of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of **random seed**

Escentially what the random seed does is "flavour" the randomness

In [ ]:
# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.2774, 0.6322, 0.5642, 0.7233],
        [0.8604, 0.2194, 0.5457, 0.7322],
        [0.5857, 0.0496, 0.5683, 0.7843]])
tensor([[0.9845, 0.4382, 0.7203, 0.6512],
        [0.7959, 0.9827, 0.4203, 0.8682],
        [0.1148, 0.2977, 0.1847, 0.3318]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's make some random but reprodocible tensors

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPU's (and making faster computations)

GPU's = faster computation on numbers, thansks to CUDA + NVIDIA hardware _ PyTorch working behind the scenes to make everything work like a well oiled machine(hunky dory -> good)

### 1. Getting a GPU

1. Easiest - Use Google colab for a free GPU(Options to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU, there's a lot of options...

3. Use cloud comouting - GCP, AQS, Azure, these services allow you to rent computers on the cloud and access them

For 2, 3 PyTorch + GPU drivers (CUDA) takes a little bit of sttting up, to do this, refer to PyTorch setup documentation - https://pytorch.org/get-started/locally/

### Check for GPU access with PyTorch

In [ ]:
# Check for GPU accesss with PyTorch
torch.cuda.is_available() # We are not using Google colab GPU at the moment

False

In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [ ]:
# Count the number of devices
torch.cuda.device_count() # as we are not using any GPU at the moment

0

## 3. Putting tensors (and models) on the GPU
The reason we want our tensors/models on the GPU is because using a GPU results in faster computations

In [ ]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU(if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu, tensor_on_gpu.device

(tensor([1, 2, 3]), device(type='cpu'))

### 4. Moving tensors back to CPU

In [ ]:
# If tensor is on GPU, can't transform it to NumPy
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()

tensor_back_on_cpu

array([1, 2, 3])