In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


## Introduction to Tensors

### Creating Tensors

In [2]:
# Scaler
scaler = torch.tensor(7)
scaler

tensor(7)

In [3]:
# Scaler have no dimention
scaler.ndim

0

In [4]:
# Get tensor back as a Python int
scaler.item()

7

In [5]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[7,9],[9,10]])
MATRIX

tensor([[ 7,  9],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 9])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR[0][2][1]

tensor(4)

In [16]:
tensor1 = torch.tensor([[
    [1,2,3],
    [4,5,6],
    [7,8,9]
],[
    [10,11,12],
    [13,14,15],
    [16,17,18]
]])
tensor1

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])

In [17]:
tensor1[1][1][2]

tensor(15)

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networds learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [18]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.5714, 0.5389, 0.4466, 0.5964],
        [0.6144, 0.3055, 0.4126, 0.1934],
        [0.9293, 0.6747, 0.2534, 0.3634]])

In [19]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # color channel, height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeroes and ones

In [20]:
# Create a tensor of all zeroes
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
# Create a tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [23]:
one_to_ten = torch.arange(0, 11, 1) # or torch.arange(start = 0, end = 1000, step = 77)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
# Create tensors like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

**Note:** Tensor datatypes is one of the 3 bug errors you'll run into with PyTorch and deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [25]:
# FLoat 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None, # What datatype is tensor
                               device = None, # What deviec is your tensor on
                               requires_grad = False) # Whether or not track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [26]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [27]:
 float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [28]:
int_32_tensor = torch.tensor([3,6,9],
                             dtype = torch.int64)
int_32_tensor

tensor([3, 6, 9])

In [29]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

# Getting information from tensors(tensor attributes)

1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [30]:
# Creat a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.3116, 0.5650, 0.1451, 0.4255],
        [0.7077, 0.6822, 0.3320, 0.2213],
        [0.2007, 0.4318, 0.0578, 0.7351]])

In [31]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.3116, 0.5650, 0.1451, 0.4255],
        [0.7077, 0.6822, 0.3320, 0.2213],
        [0.2007, 0.4318, 0.0578, 0.7351]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include
* Addition
* Subtraction
* Multiplication
* Division
* Martix manupulation

In [32]:
# Create a Tensor
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [33]:
# Multiply by 10
tensor * 10

tensor([10, 20, 30])

In [34]:
# Substract 10
tensor - 10

tensor([-9, -8, -7])

In [35]:
# Try out tensor in-buils function
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [36]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimension** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work

2. The resulting matrix has the shape if the **outer dimernsions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`

In [45]:
torch.rand(3,2)

tensor([[0.3861, 0.2198],
        [0.7430, 0.3324],
        [0.3986, 0.2598]])

In [50]:
torch.matmul(torch.rand(3, 10), torch.rand(10, 3))

tensor([[2.0364, 2.3116, 2.1902],
        [2.5181, 2.3701, 2.7653],
        [3.1867, 2.5218, 3.7301]])

In [37]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [38]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [41]:
%%time
# Matrix Multiplication by hand
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]

print(value)

tensor(14)
CPU times: user 1e+03 µs, sys: 1.03 ms, total: 2.03 ms
Wall time: 3.23 ms


In [42]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 809 µs, sys: 0 ns, total: 809 µs
Wall time: 637 µs


tensor(14)

### One of the most common errors in deep learining: shape errors

In [54]:
# Shapes for matrix multiplications
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                        [8,11],
                        [9, 12]])

#torch.mm(tensor_A, tensor_B) # torch.mm does the same job as matmul
torch.matmul(tensor_A, tensor_B) # This tensor will throw an error since the shape is(3, 2) (3, 2)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [55]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix the tensor shape issues, we can manipulate the shape of our tensors using a **Transpose**

A **transpose** switches the axes or dimensions of a given tensor

In [60]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [61]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [63]:
# The matrix manilulation operation words when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimension must match")
print("Output: \n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"Output shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimension must match
Output: 

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
Output shape: torch.Size([3, 3])
